name: Split Monorepo

on:
  push:
    tags:
      - '*'
    branches:
      - 'master'

jobs:
  split_monorepo:
    name:    Split Monorepo
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        # define package to repository map
        package:
          # Bundles
          - local_path:       'Bundle/DependencyInjectionBundle'
            split_repository: 'dependency-injection-bundle'
          - local_path:       'Bundle/FoundationBundle'
            split_repository: 'foundation-bundle'
          - local_path:       'Bundle/RoutingBundle'
            split_repository: 'routing-bundle'
          - local_path:       'Bundle/DatabaseBundle'
            split_repository: 'database-bundle'
          - local_path:       'Bundle/EloquentBundle'
            split_repository: 'eloquent-bundle'
          - local_path:       'Bundle/AnnotationBundle'
            split_repository: 'annotation-bundle'
          - local_path:       'Bundle/RedisBundle'
            split_repository: 'redis-bundle'
          - local_path:       'Bundle/CacheBundle'
            split_repository: 'cache-bundle'
          - local_path:       'Bundle/BusBundle'
            split_repository: 'bus-bundle'
          - local_path:       'Bundle/QueueBundle'
            split_repository: 'queue-bundle'
          - local_path:       'Bundle/TranslationBundle'
            split_repository: 'translation-bundle'
          - local_path:       'Bundle/ValidationBundle'
            split_repository: 'validation-bundle'
          - local_path:       'Bundle/SerializerBundle'
            split_repository: 'serializer-bundle'
          - local_path:       'Bundle/ResourceBundle'
            split_repository: 'resource-bundle'
          - local_path:       'Bundle/ConsoleBundle'
            split_repository: 'console-bundle'
          - local_path:       'Bundle/AuthBundle'
            split_repository: 'auth-bundle'
          - local_path:       'Bundle/OctaneBundle'
            split_repository: 'octane-bundle'
          - local_path:       'Bundle/PaginationBundle'
            split_repository: 'pagination-bundle'
          - local_path:       'Bundle/EventBundle'
            split_repository: 'event-bundle'
          - local_path:       'Bundle/HorizonBundle'
            split_repository: 'horizon-bundle'

          # Components
          - local_path:       'Component/Config'
            split_repository: 'config'
          - local_path:       'Component/DependencyInjection'
            split_repository: 'dependency-injection'
          - local_path:       'Component/Foundation'
            split_repository: 'foundation'
          - local_path:       'Component/Routing'
            split_repository: 'routing'
          - local_path:       'Component/Eloquent'
            split_repository: 'eloquent'
          - local_path:       'Component/Annotation'
            split_repository: 'annotation'
          - local_path:       'Component/Bus'
            split_repository: 'bus'
          - local_path:       'Component/Queue'
            split_repository: 'queue'
          - local_path:       'Component/Validation'
            split_repository: 'validation'
          - local_path:       'Component/Transformer'
            split_repository: 'transformer'
          - local_path:       'Component/Resource'
            split_repository: 'resource'
          - local_path:       'Component/Event'
            split_repository: 'event'

          # Contracts
          - local_path:       'Contracts/Config'
            split_repository: 'config-contracts'
          - local_path:       'Contracts/DependencyInjection'
            split_repository: 'dependency-injection-contracts'
          - local_path:       'Contracts/Foundation'
            split_repository: 'foundation-contracts'
          - local_path:       'Contracts/Routing'
            split_repository: 'routing-contracts'
          - local_path:       'Contracts/Eloquent'
            split_repository: 'eloquent-contracts'
          - local_path:       'Contracts/Annotation'
            split_repository: 'annotation-contracts'
          - local_path:       'Contracts/Bus'
            split_repository: 'bus-contracts'
          - local_path:       'Contracts/Validation'
            split_repository: 'validation-contracts'
          - local_path:       'Contracts/Transformer'
            split_repository: 'transformer-contracts'
          - local_path:       'Contracts/Resource'
            split_repository: 'resource-contracts'
          - local_path:       'Contracts/Event'
            split_repository: 'event-contracts'

          # Annotations
          - local_path:       'Annotations/Eloquent'
            split_repository: 'eloquent-annotations'
          - local_path:       'Annotations/Bus'
            split_repository: 'bus-annotations'
          - local_path:       'Annotations/DependencyInjection'
            split_repository: 'dependency-injection-annotations'
          - local_path:       'Annotations/Console'
            split_repository: 'console-annotations'
          - local_path:       'Annotations/Resource'
            split_repository: 'resource-annotations'
          - local_path:       'Annotations/Routing'
            split_repository: 'routing-annotations'
          - local_path:       'Annotations/Auth'
            split_repository: 'auth-annotations'
          - local_path:       'Annotations/Event'
            split_repository: 'event-annotations'

    steps:
      - uses: actions/checkout@v2

      # no tag
      - if:   "!startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Split of ${{ matrix.package }}
        uses: "symplify/monorepo-split-github-action@2.1"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          branch:                  "master"
          package_directory:       'src/${{ matrix.package.local_path }}'
          repository_organization: 'pandawa'
          repository_name:         '${{ matrix.package.split_repository }}'
          user_name:               "pandawabot"
          user_email:              "dev@pandawa.io"

      # with tag
      - if:   "startsWith(github.ref, 'refs/tags/')"
        name: Monorepo Tagged Split of ${{ matrix.package }}
        uses: "symplify/monorepo-split-github-action@2.1"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        with:
          tag:                     ${GITHUB_REF#refs/tags/}
          branch:                  "master"
          package_directory:       'src/${{ matrix.package.local_path }}'
          repository_organization: 'pandawa'
          repository_name:         '${{ matrix.package.split_repository }}'
          user_name:               "pandawabot"
          user_email:              "dev@pandawa.io"
